 set rnu
 set expandtab
 set tabstop=4
 set shiftwidth=4
 set autoindent
 set nostartofline
 set smartindent
 set wildmode=longest,list
 set cursorline
 set incsearch
 set hlsearch
 set ignorecase
 set smartcase
